from datetime import date
month_year_stamp = date.today().strftime("%b_%Y")
species_assembly_counts = 'species_counts_' + month_year_stamp + '.txt'

configfile: "config.yaml"

rule species_count:
    output:
          species_assembly_counts      
    shell:
        "python assemblydb_entrez_query.py {config[email]} {config[api_key]}"


rule retrieve_id_list:
    input:
        species_assembly_counts
    output:
        "id_list_major/{sample}_idlist.txt"
    shell:
        "python idlist_retriever.py {config[email]} {config[api_key]} {input}"
